// @generated by protoc-gen-connect-web v0.11.0 with parameter "target=ts"
// @generated from file chat.proto (package chat, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MessageRequest, MessageResponse } from "./chat_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chat.ChatService
 */
export const ChatService = {
  typeName: "chat.ChatService",
  methods: {
    /**
     * Bidirecional
     *
     * @generated from rpc chat.ChatService.StreamMessages
     */
    streamMessages: {
      name: "StreamMessages",
      I: MessageRequest,
      O: MessageResponse,
      kind: MethodKind.BiDiStreaming,
    },
  }
} as const;

